### ISSUE TITLE
Next query paramater is not used when enabling 2FA

### ISSUE THREAD

**Issue by JelteF** [valohai/django-allauth-2fa#43]
Allauth uses a next GET parameter to get to redirect the user back to the page he tried to visit if it was auth only and the user was not logged in. After entering login credentials the next parameter is thrown away on the two-factor-authenticate page. This shouldn't happen, because now the user is redirected to the main login page instead of the page he tried to visit.

**Comment by humrochagf** [comment]
I am currently working in a fix that pass forward all get parameters to address this issue and others like GA GET tracking parameters

**Comment by humrochagf** [comment]
I was running the code tests and stumbled in 7 errors. Inspecting the travis build history i noticed that there are 7 tests being skipped, there is a special reason for that?

**Comment by clokep** [comment]
@humrochagf Some tests only run under Django 1.10.

**Comment by humrochagf** [comment]
this PR #44 should solve this issue

**Comment by JelteF** [comment]
This should be fixed now as #44 is merged.

**Comment by ssimono** [comment]
Hello guys sorry to awake this issue, but I am still experiencing the problem.

The PR #44 seems to make sure that when I visit `/two-factor-authenticate?next=/my/path` then the query parameter is passed correctly.

But I think there is still a problem before: when submitting the first user/password form, the next parameter might be passed with a POST parameter, and when this happens the next path is lost. And the default template for allauth actually passes the next [as a POST parameter](https://github.com/pennersr/django-allauth/blob/master/allauth/templates/account/login.html#L40), and not as a url query.

See attached screenshot, I end up in `accounts/profile` instead of my desired path

![screenshot from 2017-06-27 16-33-30](https://user-images.githubusercontent.com/2179169/27593161-b3e301ae-5b56-11e7-819c-7ffefdb7a04c.png)


I am running Django **1.11**, allauth **0.32** and allauth-2fa **0.4.4**

**Comment by ssimono** [comment]
FYI I went around this problem by overriding the default allauth login template with something like this

```html
<form class="login" method="POST" action="{% url 'account_login' %}{% if redirect_field_value %}?{{ redirect_field_name }}={{ redirect_field_value }}{% endif %}">
```

so the form's `action` attribute takes next parameter into account. But maybe allauth-2fa could benefit from handling the next parameter with POST as well

**Comment by clokep** [comment]
@ssimono Can you please file a new issue? It's easier to track instead of commenting on old issues. Thanks.

**Comment by ssimono** [comment]
Done: #51 

Thanks
